### PR TITLE
use the right URL for 'forgot password' link

### PR DESCRIPTION
**Pull request by landryb**
TBD: testing, + adding the 'create account' link.

### CODE REVIEW

**Comment by landryb** [comment]
image

both links point to the right georchestra-specific urls.

(yeah i know i hardcoded 'créer un compte' but that would mean readding strings to message.properties files which arent in the repo...)

**Review by tkohr — APPROVED** [review]
Looks good and sends to correct URLs. Thanks @landryb !

Just a bit of a shame, as you mentioned, that we end up with a mixed language template and no english translation for "S'inscrire". Could it be an alternative to just set a translation key in this PR and set its values (for FR and EN) in https://github.com/georchestra/georchestra/tree/master/cas-server-webapp/src/main/resources?

**Comment by landryb** [comment]
> Could it be an alternative to just set a translation key in this PR and set its values (for FR and EN) in https://github.com/georchestra/georchestra/tree/master/cas-server-webapp/src/main/resources?

well i dunno how the translations/resources would merge/override the other ones shipped inside cas6 (which arent the ones you link to), so i didnt explore this. Left as an exercise to the next one working on cas6 :)

**Comment by tkohr** [comment]
Hum, yep kind of difficult to test the translation behavior from here.

I added a small PR adapting the login UI on top of this one. Feel free to comment!

**Pull request merged**
