### PR TITLE
add dependencies for memcached ticket registry support

### PR DESCRIPTION
**Pull request by landryb**
with that, i have the jars for cas tickets in memcached (untested at runtime yet)
```
[22/06 11:21] landry@ids3.fluela:/etc/georchestra/cas $unzip -l /usr/share/lib/georchestra-cas/cas.war |grep memcache
     6420  2022-06-22 11:05   WEB-INF/lib/cas-server-support-memcached-ticket-registry-6.3.7.4.jar
    23156  2022-06-22 11:05   WEB-INF/lib/cas-server-support-memcached-core-6.3.7.4.jar
      709  2022-06-22 11:05   WEB-INF/lib/cas-server-support-memcached-spy-6.3.7.4.jar
   473774  2022-06-14 15:54   WEB-INF/lib/spymemcached-2.12.3.jar
```

cf https://apereo.github.io/cas/6.4.x/ticketing/Memcached-Ticket-Registry.html

sample config in `cas/config/cas.properties` (cf https://apereo.github.io/cas/6.4.x/ticketing/Memcached-Ticket-Registry.html#configuration, untested too yet):
```
cas.ticket.registry.memcached.memcached.servers=memcached:11211
cas.ticket.registry.memcached.memcached.locator-type=ARRAY_MOD
cas.ticket.registry.memcached.memcached.failure-mode=Redistribute
cas.ticket.registry.memcached.memcached.hash-algorithm=FNV1_64_HASH
```

### CODE REVIEW

**Review by pmauduit — APPROVED** [review]
LGTM, I'd expect that without extra configuration in the cas.properties, CAS won't mind and not enable the feature (instead of crashing at bootstrap)

**Comment by landryb** [comment]
runtime-tested ok with the following:
```
cas.ticket.registry.memcached.servers=memcache:11211
cas.ticket.registry.memcached.locator-type=ARRAY_MOD
cas.ticket.registry.memcached.failure-mode=Redistribute
cas.ticket.registry.memcached.hash-algorithm=FNV1_64_HASH
cas.ticket.registry.memcached.transcoder=KRYO
```

i have to admit that with the memcached lines commented out, it seemed to try reaching a memcached on localhost:11211 so im not sure it doesnt 'enable' the feature at runtime by default if built in..... maybe another setting is needed to select the ticket registry type ?

**Comment by pmauduit** [comment]
> so im not sure it doesnt 'enable' the feature at runtime by default if built in.....

Does it silently fail, and then fallback on the default ticket registry, or is cas unable to boot ?

**Comment by landryb** [comment]
> > so im not sure it doesnt 'enable' the feature at runtime by default if built in.....
> 
> Does it silently fail, and then fallback on the default ticket registry, or is cas unable to boot ?

from my limited testing, it booted, but trying to auth against it failed because it tried to talk to a missing memcached on localhost (eg default config values)

**Comment by landryb** [comment]
thanks for merging, but was it tested to work fine without a running memcached ? in my previous testing (https://github.com/georchestra/georchestra-cas-server/pull/12#issuecomment-1163053965)  it didnt..

**Comment by fvanderbiest** [comment]
Oops, not to my knowledge, but since I saw a GO from @pmauduit ...

**Comment by fvanderbiest** [comment]
Fails indeed. I'll revert.
```
cas_1                                | 2023-04-02 15:32:15.376 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=4, #iq=0, topRop=null, topWop=Cmd: set Key: TGT-1-wJ0HatG1HbKowKTlJ6Qe43tNjQjaBC8RzLEAOR4Dr9mYSVR7CsyloMWSFoplPJPW9qY-5dcd84e5c177 Flags: 0 Exp: 28800 Data Length: 508, toWrite=0, interested=0}
cas_1                                | 2023-04-02 15:32:15.377 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=4, #iq=0, topRop=null, topWop=Cmd: set Key: TGT-1-wJ0HatG1HbKowKTlJ6Qe43tNjQjaBC8RzLEAOR4Dr9mYSVR7CsyloMWSFoplPJPW9qY-5dcd84e5c177 Flags: 0 Exp: 28800 Data Length: 508, toWrite=0, interested=0}
cas_1                                | java.net.ConnectException: Connection refused
cas_1                                | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
cas_1                                | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
cas_1                                | 	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
cas_1                                | 	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
cas_1                                | 	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
cas_1                                | 2023-04-02 15:32:15.378 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=4, #iq=0, topRop=null, topWop=Cmd: set Key: TGT-1-wJ0HatG1HbKowKTlJ6Qe43tNjQjaBC8RzLEAOR4Dr9mYSVR7CsyloMWSFoplPJPW9qY-5dcd84e5c177 Flags: 0 Exp: 28800 Data Length: 508, toWrite=0, interested=0}, attempt 7.
cas_1                                | 2023-04-02 15:32:23.756 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=21, #iq=0, topRop=null, topWop=Cmd: get Keys: TGT-1-wJ0HatG1HbKowKTlJ6Qe43tNjQjaBC8RzLEAOR4Dr9mYSVR7CsyloMWSFoplPJPW9qY-5dcd84e5c177Exp: 0, toWrite=0, interested=0}
cas_1                                | 2023-04-02 15:32:23.757 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=21, #iq=0, topRop=null, topWop=Cmd: get Keys: TGT-1-wJ0HatG1HbKowKTlJ6Qe43tNjQjaBC8RzLEAOR4Dr9mYSVR7CsyloMWSFoplPJPW9qY-5dcd84e5c177Exp: 0, toWrite=0, interested=0}
cas_1                                | java.net.ConnectException: Connection refused
cas_1                                | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
cas_1                                | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
cas_1                                | 	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
cas_1                                | 	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
cas_1                                | 	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
cas_1                                | 2023-04-02 15:32:23.757 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=21, #iq=0, topRop=null, topWop=Cmd: get Keys: TGT-1-wJ0HatG1HbKowKTlJ6Qe43tNjQjaBC8RzLEAOR4Dr9mYSVR7CsyloMWSFoplPJPW9qY-5dcd84e5c177Exp: 0, toWrite=0, interested=0}, attempt 7.
```

**Comment by fvanderbiest** [comment]
Done with 05c9f28

**Pull request merged**
