### PR TITLE
Upgrading to CAS 6.6.15

### PR DESCRIPTION
**Pull request by pmauduit**
Tests:
* `gradle build` ok
* runtime: running the docker image fails, but launched without any datadir

To be tested more thoroughly, I'd expect that some UI adjustments / realign have to be made

### CODE REVIEW

**Comment by pmauduit** [comment]
See https://github.com/georchestra/georchestra/issues/3838

**Comment by pmauduit** [comment]
Not ready for 23.0 IMHO

**Comment by fvanderbiest** [comment]
OK, lets postpone it then.

**Comment by landryb** [comment]
last version from the same branch is now [v6.6.15](https://github.com/apereo/cas/releases/tag/v6.6.15), and the 7.0 branch is at [v7.0.2](https://github.com/apereo/cas/releases/tag/v7.0.2) ... something for the next codesprint ? or @f-necas can be tricked into looking into it ? ;)

**Comment by fvanderbiest** [comment]
> or @f-necas can be tricked into looking into it ? ;)

Err... he's very busy currently ;-)

**Comment by landryb** [comment]
with this updated PR, a cas 6.6.15 built with java 17 works fine in a tomcat running with java17, some properties have been renamed in `config/cas.properties`:
```
-cas.service-registry.initFromJson=false
+cas.service-registry.core.init-from-json=false

-cas.authn.oidc.jwks.jwks-file=file:///tmp/keystore.jwksdown
+cas.authn.oidc.jwks.file-system.jwks-file=file:///tmp/keystore.jwksdown

-cas.authn.saml-idp.core.entity-id=https://${FQDN}/idp
+cas.authn.saml-idp.core.entity-id=https://georchestra.dev.craig.fr/idp

-cas.authn.saml-idp.metadata.location=file:///tmp/
+cas.authn.saml-idp.metadata.file-system.location=file:///tmp/
```
i can login fine:
image

but the theme looks slightly broken.

image

**Comment by landryb** [comment]
ah no, the broken theme is due to the infamous "you're behind a reverse proxy so i'll redirect you in a loop" bug, worked around in georchestra/datadir@8e0a447, if i uncomment the line then the login prompt looks more or less like before, a bit too wide ?

image

**Comment by landryb** [comment]
the 'login box too wide' goes away if i drop the `flex-grow-1` css class that is automagically added to the following div:
image

but i wouldnt know what magic sets this from the html template and the cas.css we have in the repo.

**Comment by landryb** [comment]
dropping `flex-column` from https://github.com/georchestra/georchestra-cas-server/blob/master/src/main/resources/templates/georchestra/fragments/loginform.html#L16 improves the layout, but we're not there yet, as the parent div still has `flex-column` and i don't get where it comes from.

tried dropping `d-flex` from https://github.com/georchestra/georchestra-cas-server/blob/master/src/main/resources/templates/georchestra/layout.html#L35 but that didnt help.

image

@fgravin @f-necas since you're more frontend experts than me.... all i know is that bootstrap in cas 6.3 was at 4.6.0, and bootstrap in cas 6.6 is at 5.2.0.

**Comment by f-necas** [comment]
Solved ! Thanks to @tkohr for mentionning apereo's template. 

Source of the magical things : https://github.com/apereo/cas/blob/6.6.x/support/cas-server-support-thymeleaf/src/main/resources/templates/login/casLoginView.html#L15C101-L15C109

**Comment by pmauduit** [comment]
pretty cool if it does not require tons of gradle shenanigans to upgrade :-) LGTM

**Pull request merged**
